#!/bin/sh

DIR=/home/pi/herold/pibot
DAEMON=bin/hubot
ENVFILE=$DIR/.env
DAEMON_NAME=pibot
DAEMON_OPTS="--adapter slack"
USER=root
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:$DIR/node_modules:$DIR/node_modules/hubot/node_modules

LOGFILE=/var/log/$DAEMON_NAME.log
PIDFILE=/var/run/$DAEMON_NAME.pid
 
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    . $ENVFILE
    start-stop-daemon --no-close --user $USER --start --pidfile $PIDFILE -c $USER:$GROUP \
      --make-pidfile \
      --background --chdir $DIR --exec $DAEMON -- \
        $DAEMON_ARGS >> $LOGFILE 2>&1 || return 23

    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
